### PR TITLE
Fixed Cache-Id

### PR DESCRIPTION
**Pull request by muratulashozturk**
Fixes Cache-Id and login issues.

### CODE REVIEW

**Comment by Dumpff** [comment]
How can i fix that error?

**Review by ButCheR-PRO — APPROVED** [review]
Thx

**Review by ButCheR-PRO — APPROVED** [review]

**Comment by Aka-Bobur** [comment]
Works for me, Thnx Bro

**Comment by GeRRyOD** [comment]
I still have a problem, don't understand how to resolve. I've maid all thinks that you gaved, but after bot run i still have errors. And yes, i am using http proxy

Traceback (most recent call last):
  File "/root/TapSwapBot/bot/core/tapper.py", line 112, in login
    chq_result, cache_id_result = extract_chq(chq=chq)
  File "/root/TapSwapBot/bot/utils/scripts.py", line 132, in extract_chq
    driver = web_driver(service=web_service(webdriver_path), options=options)
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py",
 line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Failed to read marionette port

**Comment by ButCheR-PRO** [comment]
Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
ERROR    | 393 | Unknown error: cannot unpack non-iterable NoneType object

**Pull request merged**
