### PR TITLE
Fixed Current Error

### PR DESCRIPTION
**Pull request by enolife**
Fixed and working

### CODE REVIEW

**Comment by ButCheR-PRO** [comment]
Thx, working!

**Review by ButCheR-PRO — APPROVED** [review]
Working

**Review by ButCheR-PRO — APPROVED** [review]

**Comment by faruqmr** [comment]
Thanks!

**Comment by dkryshtopenkomck** [comment]
@shamhi fyi^

**Comment by Visualua** [comment]
image
But it didn't work for long :)

**Comment by ButCheR-PRO** [comment]
Not working again :(

**Comment by MasudsCloud** [comment]
Not works.

**Comment by dkryshtopenkomck** [comment]
doesn't work @enolife

**Pull request closed without merging**
